<?php

namespace BlueIcons\FacebookInterfaceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IncomingPayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomingPayRepository extends EntityRepository
{
}