using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace BlueIkons_DB
{
    /// <summary>
    /// Controller class for FBUsers
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class FBUserController
    {
        // Preload our schema..
        FBUser thisSchemaLoad = new FBUser();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public FBUserCollection FetchAll()
        {
            FBUserCollection coll = new FBUserCollection();
            Query qry = new Query(FBUser.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public FBUserCollection FetchByID(object Fbid)
        {
            FBUserCollection coll = new FBUserCollection().Where("fbid", Fbid).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public FBUserCollection FetchByQuery(Query qry)
        {
            FBUserCollection coll = new FBUserCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Fbid)
        {
            return (FBUser.Delete(Fbid) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Fbid)
        {
            return (FBUser.Destroy(Fbid) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(long Fbid,string FirstName,string LastName,string Fbemail,string Paypalemail,DateTime? CreatedDate,DateTime? LastChanged,string AccessToken)
	    {
		    FBUser item = new FBUser();
		    
            item.Fbid = Fbid;
            
            item.FirstName = FirstName;
            
            item.LastName = LastName;
            
            item.Fbemail = Fbemail;
            
            item.Paypalemail = Paypalemail;
            
            item.CreatedDate = CreatedDate;
            
            item.LastChanged = LastChanged;
            
            item.AccessToken = AccessToken;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(long Fbid,string FirstName,string LastName,string Fbemail,string Paypalemail,DateTime? CreatedDate,DateTime? LastChanged,string AccessToken)
	    {
		    FBUser item = new FBUser();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Fbid = Fbid;
				
			item.FirstName = FirstName;
				
			item.LastName = LastName;
				
			item.Fbemail = Fbemail;
				
			item.Paypalemail = Paypalemail;
				
			item.CreatedDate = CreatedDate;
				
			item.LastChanged = LastChanged;
				
			item.AccessToken = AccessToken;
				
	        item.Save(UserName);
	    }
    }
}
