using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace BlueIkons_DB
{
    /// <summary>
    /// Controller class for Gift
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class GiftController
    {
        // Preload our schema..
        Gift thisSchemaLoad = new Gift();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public GiftCollection FetchAll()
        {
            GiftCollection coll = new GiftCollection();
            Query qry = new Query(Gift.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public GiftCollection FetchByID(object GiftKey)
        {
            GiftCollection coll = new GiftCollection().Where("Gift_Key", GiftKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public GiftCollection FetchByQuery(Query qry)
        {
            GiftCollection coll = new GiftCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object GiftKey)
        {
            return (Gift.Delete(GiftKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object GiftKey)
        {
            return (Gift.Destroy(GiftKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(long? SenderFbid,long? ReceiverFbid,string ReceiverEmail,string WittyMessage,DateTime? CreatedDate,int? Blueikon,bool? Fbpost,string ReceiverName)
	    {
		    Gift item = new Gift();
		    
            item.SenderFbid = SenderFbid;
            
            item.ReceiverFbid = ReceiverFbid;
            
            item.ReceiverEmail = ReceiverEmail;
            
            item.WittyMessage = WittyMessage;
            
            item.CreatedDate = CreatedDate;
            
            item.Blueikon = Blueikon;
            
            item.Fbpost = Fbpost;
            
            item.ReceiverName = ReceiverName;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int GiftKey,long? SenderFbid,long? ReceiverFbid,string ReceiverEmail,string WittyMessage,DateTime? CreatedDate,int? Blueikon,bool? Fbpost,string ReceiverName)
	    {
		    Gift item = new Gift();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.GiftKey = GiftKey;
				
			item.SenderFbid = SenderFbid;
				
			item.ReceiverFbid = ReceiverFbid;
				
			item.ReceiverEmail = ReceiverEmail;
				
			item.WittyMessage = WittyMessage;
				
			item.CreatedDate = CreatedDate;
				
			item.Blueikon = Blueikon;
				
			item.Fbpost = Fbpost;
				
			item.ReceiverName = ReceiverName;
				
	        item.Save(UserName);
	    }
    }
}
